services:
    cache-service:
        build: ./cache-service
        volumes:
            - ./cache-service:/web
            - /web/node_modules
        ports:
            - '5000:5000'
        working_dir: /web
        environment:
            - PORT=5000
        command: yarn dev

    apibreaker:
        image: nginx:latest
        volumes:
            - ./nginx/apibreaker.conf:/etc/nginx/nginx.conf
        ports:
            - '8090:80'
